from enum import IntEnum


class ParsecAuthenticationType(IntEnum):
    NO_AUTH = 0x0
    DIRECT_AUTH = 0x1
    TOKEN_AUTH = 0x2
    UNIX_PEER_AUTH = 0x3
    JWT_VID_AUTH = 0x4

class ParsecMessageErrorType(IntEnum):
    """Represents the type of error returned by the Parsec message."""
    SUCCESS = 0
    WRONG_PROVIDER_ID = 1
    CONTENT_TYPE_UNSUPPORTED = 2
    ACCEPT_TYPE_UNSUPPORTED = 3
    WIRE_PROTOCOL_VER_UNSUPPORTED = 4
    PROVIDER_NOT_REGISTERED = 5
    INVALID_PROVIDER = 6
    BODY_DESERIALISE_FAILED = 7
    BODY_SERIALISE_FAILED = 8
    INVALID_OPCODE = 9
    RESPONSE_TOO_LARGE = 10
    AUTH_ERROR = 11
    AUTH_NOT_EXIST = 12
    AUTH_NOT_REGISTERED = 13
    KEY_INFO_MANAGER_ERROR = 14
    CONNECTION_ERROR = 15
    INVALID_ENCODING = 16
    INVALID_HEADER = 17
    WRONG_PROVIDER_UUID = 18
    NOT_AUTHENTICATED = 19
    BODY_SIZE_EXCEEDS_LIMIT = 20
    ADMIN_REQUIRED = 21
    PSA_GENERIC_ERROR = 1132
    PSA_NOT_PERMITTED = 1133
    PSA_NOT_SUPPORTED = 1134
    PSA_INVALID_ARG = 1135
    PSA_INVALID_HANDLE = 1136
    PSA_BAD_STATE = 1137
    PSA_BUF_TOO_SMALL = 1138
    PSA_ALREADY_EXISTS = 1139
    PSA_DOES_NOT_EXIST = 1140
    PSA_INSUFFICIENT_MEMORY = 1141
    PSA_INSUFFICIENT_STORAGE = 1142
    PSA_INSUFFICIENT_DATA = 1143
    PSA_COMMS_FAILURE = 1145
    PSA_STORAGE_FAILURE = 1146
    PSA_HARDWARE_FAILURE = 1147
    PSA_INSUFFICIENT_ENTROPY = 1148
    PSA_INVALID_SIG = 1149
    PSA_INVALID_PADDING = 1150
    PSA_TAMPERED = 1151
    PSA_CORRUPTED = 1152
    
class ParsecMessageOpcode(IntEnum):
    """Represents the operation being carried out by the Parsec message."""
    NOOP = 0
    OP_PING = 1
    OP_PSA_GENERATE_KEY = 2
    OP_PSA_DESTROY_KEY = 3
    OP_PSA_SIGN_HASH = 4
    OP_PSA_VERIFY_HASH = 5
    OP_PSA_IMPORT_KEY = 6
    OP_PSA_EXPORT_PUBLIC_KEY = 7
    OP_LIST_PROVIDERS = 8
    OP_LIST_OPCODES = 9
    OP_PSA_ASYMMETRIC_ENCRYPT = 0xA
    OP_PSA_ASYMMETRIC_DECRYPT = 0xB
    OP_PSA_EXPORT_KEY = 0xC
    OP_PSA_GENERATE_RANDOM = 0xD
    OP_LIST_AUTHENTICATORS = 0xE
    OP_PSA_HASH_COMPUTE = 0xF
    OP_PSA_HASH_COMPARE = 0x10
    OP_PSA_AEAD_ENCRYPT = 0x11
    OP_PSA_AEAD_DECRYPT = 0x12
    OP_PSA_RAW_KEY_AGREEMENT = 0x13
    OP_PSA_CIPHER_ENCRYPT = 0x14
    OP_PSA_CIPHER_DECRYPT = 0x15
    OP_PSA_MAC_COMPUTE = 0x16
    OP_PSA_MAC_VERIFY = 0x17
    OP_PSA_SIGN_MESSAGE = 0x18
    OP_PSA_VERIFY_MESSAGE = 0x19
    OP_LIST_KEYS = 0x1A
    OP_LIST_CLIENTS = 0x1B
    OP_DELETE_CLIENT = 0x1C
    OP_ATTEST_KEY = 0x1E
    OP_PREPARE_KEY_ATTESTATION = 0x1F
    OP_CAN_DO_CRYPTO = 0x20